‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
([[This file was protected with MoonSec V3]]):gsub('.+', (function(a) _syfZDfAWbj_y = a; end)); return(function(g,...)local r;local l;local b;local f;local o;local t;local e=24915;local n=0;local d={};while n<629 do n=n+1;while n<0x268 and e%0x2176<0x10bb do n=n+1 e=(e*368)%31205 local u=n+e if(e%0x3f40)>0x1fa0 then e=(e*0x3ab)%0x2cd9 while n<0x2ee and e%0x7e0<0x3f0 do n=n+1 e=(e-513)%46002 local t=n+e if(e%0xe10)<0x708 then e=(e*0x362)%0x436e local e=8254 if not d[e]then d[e]=0x1 f=string;end elseif e%2~=0 then e=(e+0x39d)%0x427 local e=8403 if not d[e]then d[e]=0x1 r={};end else e=(e-0x327)%0x7be4 n=n+1 local e=85157 if not d[e]then d[e]=0x1 l=getfenv and getfenv();end end end elseif e%2~=0 then e=(e-0x5c)%0xc44 while n<0x3a3 and e%0x40e6<0x2073 do n=n+1 e=(e*821)%26715 local u=n+e if(e%0x36a4)>0x1b52 then e=(e+0x1b8)%0x50d1 local e=18641 if not d[e]then d[e]=0x1 o="\4\8\116\111\110\117\109\98\101\114\108\102\100\76\80\82\72\85\0\6\115\116\114\105\110\103\4\99\104\97\114\83\102\71\104\103\108\104\112\0\6\115\116\114\105\110\103\3\115\117\98\80\70\72\76\103\98\73\117\0\6\115\116\114\105\110\103\4\98\121\116\101\75\72\75\71\99\108\113\111\0\5\116\97\98\108\101\6\99\111\110\99\97\116\89\98\79\110\80\74\102\101\0\5\116\97\98\108\101\6\105\110\115\101\114\116\66\86\87\84\87\107\118\69\5";end elseif e%2~=0 then e=(e*0x1fb)%0x42cd local e=72497 if not d[e]then d[e]=0x1 t=function(d)local e=0x01 local function n(n)e=e+n return d:sub(e-n,e-0x01)end while true do local d=n(0x01)if(d=="\5")then break end local e=f.byte(n(0x01))local e=n(e)if d=="\2"then e=r.lfdLPRHU(e)elseif d=="\3"then e=e~="\0"elseif d=="\6"then l[e]=function(n,e)return g(8,nil,g,e,n)end elseif d=="\4"then e=l[e]elseif d=="\0"then e=l[e][n(f.byte(n(0x01)))];end local n=n(0x08)r[n]=e end end end else e=(e-0xfe)%0x54e1 n=n+1 local e=54049 if not d[e]then d[e]=0x1 end end end else e=(e+0x392)%0x5773 n=n+1 while n<0x1dd and e%0x1abe<0xd5f do n=n+1 e=(e*249)%46323 local t=n+e if(e%0x4914)>0x248a then e=(e+0x316)%0x4413 local e=82002 if not d[e]then d[e]=0x1 end elseif e%2~=0 then e=(e-0x2e3)%0x5d55 local e=99291 if not d[e]then d[e]=0x1 b=tonumber;end else e=(e-0x30e)%0x14c8 n=n+1 local e=69468 if not d[e]then d[e]=0x1 l=(not l)and _ENV or l;end end end end end e=(e+88)%15800 end t(o);local n={};for e=0x0,0xff do local d=r.SfGhglhp(e);n[e]=d;n[d]=e;end local function u(e)return n[e];end local u=(function(o,t)local g,d=0x01,0x10 local n={{},{},{}}local l=-0x01 local e=0x01 local f=o while true do n[0x03][r.PFHLgbIu(t,e,(function()e=g+e return e-0x01 end)())]=(function()l=l+0x01 return l end)()if l==(0x0f)then l=""d=0x000 break end end local l=#t while e<l+0x01 do n[0x02][d]=r.PFHLgbIu(t,e,(function()e=g+e return e-0x01 end)())d=d+0x01 if d%0x02==0x00 then d=0x00 r.BVWTWkvE(n[0x01],(u((((n[0x03][n[0x02][0x00]]or 0x00)*0x10)+(n[0x03][n[0x02][0x01]]or 0x00)+f)%0x100)));f=o+f;end end return r.YbOnPJfe(n[0x01])end);t(u(105,"/%h{de7N&2Yw,O( 2,"));t(u(229,"eqxF*vA>X%p)UK^Oq)FUU*^,O%y)x)FOO>>x%^)qUO^qEKOXxU*UAxX%>)vA>xOXmAqO*vAg>xAKXOpqU^^Fxq*v^Xw>XKpp)UKUOKqFqFx#AxA>%*)vU)>U%Kxv*qvpAUXUp4v%KU^)q%xF*FF)X>>()X)A^)Kp0UU^^K>qX(p^)K>vO>#pxAv*A>AXpv)>)*U^^vrqxA^^qq%FpdUpK^Oqq)xFvqv%>v%pp^K*OvwXO>FXF)*%%p*DvO^AOUq)F>vYAxXx%A%OU*UOqxqpF%*OAqxx*xUUK*O8qvx%^vAOXFp/pUU%^UW>qOFpvq>%AXpq)U>X%vqOFFv_vU>%%U%U)^K)q>Fxq%*A>%xX**Up^>O%q%Fp*v>vAo>%)OKFUO^K)KKpAxAO%qpv)^^p^F!)E%vFAKX%pK%*A%XX Uq)*%vXqQXUpKU)^A *OKyOxAAAAUpF%2)OXp"));local e=(-15953+(function()local t,e=0,1;(function(l,n,d,e)n(d(n,d,l,e),n(d,n,e and e,n),e(l,d,d,l),e(d,e,n,d)and n(l,n,l and e,e))end)(function(f,l,n,d)if t>415 then return d end t=t+1 e=(e*430)%37093 if(e%400)<=200 then e=(e-407)%45128 return f else return d(f(l,l,l,n),f(d,d and n,l,f),n(n,d,n,n),l(d,n,d,n))end return l(d(d,n,n and d,n),n(n and f,d,f,n),n(d,l and l,d,f),l(f,f,n and f,l))end,function(l,f,d,n)if t>132 then return l end t=t+1 e=(e*71)%19298 if(e%1070)>=535 then e=(e*206)%5551 return n else return l(d(d,d and n,n,l),f(d,l,l,n),d(l and d,l,n,d)and n(d and d,d,l,f),l(l,n,n,l))end return n(f(n,d and l,f,d),f(n,n,f,f),f(f,n,n,f),l(d,n,n,d))end,function(f,n,l,d)if t>472 then return n end t=t+1 e=(e*1019)%33332 if(e%1026)>513 then return n(n(l,l and n,n,n and l),f(d,f,d,d)and n(d,d,f,f),l(d,l,d,d),l(n,d,n,n))else return f end return n end,function(d,l,f,n)if t>217 then return n end t=t+1 e=(e*504)%22615 if(e%1160)<=580 then e=(e-144)%33028 return d(l(n,f,f,d),n(f,d,n,l),f(n,d,n,n),l(n,d,n,l)and f(d,l and n,d,d))else return f end return l end)return e;end)())local h=r.PWYzzFXp or r.khhdqEcc;local fe=(getfenv)or(function()return _ENV end);local t=3;local l=2;local y=1;local o=4;local function te(s,...)local a=u(e,"D1RbNH_vg6u XL/}b_}g}N}!//}1/N/wLX16bgbNRbb1bRRNR R} H -u/ TuNus6XL6}g}NLg/6/_/H/gvugKvo_X_g 1X}XsX1 uX6_X6  g Hu=u b_b6RXRgRN_1gZvXH_gHg,vXvb_/}/1}}N}O/XbXNXN6N}}gbub6bgRL/Nbv1LR LNR:1/1v1gJH}}+X}6}NuX}}/L}N/N6gX1L}L L_ vXH }vguugbN/NXNNNmbXg_6H6L61RuRuRq1X1gv vHgev7v6_6}}}g}N}t/X/guNNR1XLuLXL&XXXgRvRXR R_16RR11f/u_ug6X6g6N}L}H}_/b}b/H}RL6vbG_O1}L}6}H}10Lg}N/HRNNN-bXg ug616/6Xg66R_bgLvL1R1HEg>Ni4NX_NHH_6H1HuR HHNHLuLgLwXXXgRuR6Ru1X _ uuXuguNkb}L4_}b-R}1} /L}u/1vugLv#_X_g 1X}X X_uv Hu}uv6v Nu/u1uR6v6}v5gLgNgJvLgRH1g7vXv_QRSX}g}N}AHHNXN6N/H.N1buN6b1NSR6Rbb1RXRbRRu/u}uNu%6XL +b#R}1X}}6/6v/v}vNvt_X /X6XbLyXvX_gRN}NgNNNMbXbg NgR_XRuR R21X1gvugRv vHH_Nvb/}u} }Y/X/gRgNHN}NXN_b}NHXuL1X- X g1bRbRHz/}//N)RL6/ }R}_/v}LgRg1vgvNviLgLvL XHX/HuH HQNXNg6vuH Ov ubuR61RubHRf1X1ggvvHgNg1RNvb_Xv11NH_H/HvH1EEH8b/h_LRLuXgXNXq&}RXR61N1}Xg/gU6V}YX}H}//}/Lg_66vXvgvN LXLXXX6gq /L1vNXHv 6g L gugHg VHMgbgL6=gbg gHv6b3B/1LQNI-}XN_H6__H1Hu11RHNubXbLb/bb/gCvR1R/RXR_161&^Lu_uH6X6g6N9C}/}1}R}Nv}vgvNvj_X_g/NuN6XHuH}HiNXNgg uH yv 6X666ggX6_gHgu1u_b1OjX{g_XvNvi_g_vRu1 1vH_N1HbA_b b6NWbUb6RRb1R 16RRk}1v1R1NG1:_Ig //}}v}1u}/6LL/1LHL_X6L1XHX}gv 6 X 1 uuL Hu6_Huu_RH66LgLNLggg1v_gR_LvuvLR}R _HHHH6Hu1vbaN6b/NubHNRNHXuX/X( X g}H1N1)}Xj61g17Lunb5gg}gggNgYvXvg NL}uX_u_ _0HXHgXb bXr v v W Hbub/brRXRg61g1gHg_vbvbv vNvbvR}/<b}N}f/XbNHbNbbLNNRNbXRLN1R6bR /XR N suX1N1b^1!Oz %g(R}H}_/ gRg8vgvNv>LbX6L1XHH/HXHNHlNX6HuHu6uubuNgbpRXRgNNggvLg bNvRv1_LvRR&_jHL_v_NH/HvHLNHNEo_L_LNXXXgXN1bRNRvR  Ru}uguNuyKu}LQ 6R6_gggNg?XbLL/gXbL1LuLuX6 } LH_H_NXNgNN b >uu6L6/6bR RNRt1X1g1N13=XIgV_B_}X}g}NH6HXN6NLHRN}Lu/HLFXXXg%gRHbR} Rb1/1}1v1y2H}R719v}6//}N/6gRgbvgvNv, XLNXHL6X1XuXvHbNXNgNNN#bX g6RvhR/R/RNRB1XH gbvXv vubv+RM_}g}N}pH}H1H1HtNgbLNvNMNH}uX_X_ X g N}11l{X}gJ1}/6uuH63gXggL_/H/X/NLLLbXLLXX6XNu}XXXbXRuLu}u6NRNbbgbNbjvN6X6g6q_bvLgg1R1Gkg&NG2vbH6HL_N/}/g/N/mLXLgLNL0XXXgXNXq L u N fuXug/}u>6X6g6N6ogXgggN61vXvgvNv1_X_g_N_RHXHgHNHRH_NgNNN-gRu1u_6Hv}gL6_6_g1gu1_RZtX3g#N_N_H_ _gH1HuN N6bNN R b6NRNRRLb_X# X g N r RuguNuq6X}H6N6)gXgggNgxvX6gv/vr_X_g_N_IH/HgvNH6NXNgNNNnbXb6bNb=b6RgR_Ry1L1g1N1OyXR>wNlT}X}u}N}1/X/g/H/cLXLgLHLJXXXgX X0 X g _ guXuguN} }uXgX1X6 u H/1gRvLvgvNvUXN_u_X_xHXHgXg } } X _u6uu6}b_bmRXRgRNRRRN1g1N15gCvvvRvH_6HuH6_R/X/u/g/.LXLgb NbN1RuXNX+ X g HX1uXuguN R}v6g6H6;g}gggNg+vXg vNvR_X_g_N_PHXHgH_H-NLNgN_NKb/bgHNN6RXR6RNR11X1}1NRR1X;gCva;}L}g}N}n}/}L/N/NLXLXLNL#XXXgX XQ L g g !u/ug _XQ6X6u6N6HgXgggNg?gHvgvvvx_L_g_N_!HXg6HNHRNXNuNNNRbXH/g_b)R/RgbbR{1L1g1u1(1yN tNZ?}XWv}N}1/X/g/X/7L}LgLvLrXXXgL_L/ X X N RuXuguNuU }6g6v6Ug}gggNgEvXX1vNvR_X_u_N_9HXHg_HHQNXNgNHN*bXbgbN/NRXRgRNRG_X1g1N1t!L-g;NSPI/Kw}N})/X}6/N/KLX/uLuL,XXXgLXX) X gLuXguXuguNu_6X666N6_gXgXXvgKvXvgvuv+_L_g_Nv1HXHgHNH1NXNgNNHRHXbgbNb0HNRgRNRVR/HX1N11oXb1%NwJ}X1g}_}&/L/g/H/q1HLg/_/NXXX XN/R X g N )Xvuguguc6L6g6N6TgX6vgNg1vXvXvNv)_X_gvg_eHXHgHNH=N/NgNNN bXbgbNb1RXRuRNRRHb1g1H1If/EgPNwk;/bg}N}R/X1g/N/ILXLg/LL!X}XgXHXy X g N buXuXuNuR6X6g6N6d6}gggvgjv/vgvgvSv/gH_N_HHX_RHNH3NXHuH(NeNRbgHLbYRXRgNNbl1X1/1N1_JXN!YN%*RL}g}6}A///g/_/!//RvLNL_XXLRXNX2 XXuXv z bugXLuS6X6g N6XgXg}gNgvvXu vNv3gJ_g_u_wH/HgH_H?_XHvNNNvbXb/bNHvRXNgbzRMRN1g1 1F1bIgRN1v}X91}N}c/X/6/N}R}uLgL}LV/uXgXNXf XLu N XuXuguNub6Xuuu_6%66gg 6gEvXvg6Nv1_XvH_N_LHX_/HN_RNLNgHRN<HXbgbNb2b/bgRNR}1XRL1N1W=X1u, +hCX}gRg}#/X/g/N/LLX/HLN/pXXXuXNLpX} gXn sLRug 1u?u/ 66N6LgX6XgNgQvX6ggHv(v6_gv1_(g6Hg__HgNXH_NN_NbXbgbNNRbuRgbbRqRH1g1N1#aXYurN5L}XGv}N}R/X}g>#/m/gLgL}LhL6Xg}NXg XXN NX4uXuuuNu9X_6g6L6P6gggg_gj6XX vNvu_Xv1_N6vHX_u_gH.HgNg_/N3bXbgbNN6RXbRRNRX1X1u1Nb=1N=gt}{4J_}gRs}a/X/L/N/ LXLuLNL1XX/gL_XVXv g / #u}ug _u_6XuH6NuLgXgggNgTgHvggRv.vN_g_N_xHX66HNHLNXHHNNN/bXbgN}b*bvRgb1R81L1gbN1NjX1bKNKu}X1 }NnRmR/g}1/,}gLgLNL+LR},XNX/ X g N 1uXu6uNu-XX6g6N6<g/gggNg4vXg/vNv _Xv__N_1HXvg_/HsHvNgN/N;N1bgN_b1RXbHRNRN1X1g1N1_bNFg1R%V}L}g}H}.///g/N1WLXLgLNLHXXXgXNXf/X g N *u/uguNuJ6XLv6N6 gX6_gNg1vXgu6NvSvv_gv__>HXHgHNHXNXHbNNN1bXbubNNRbLRgb5RfRN1g1N12wX1/ENrX}X}6}N}R/X}u}H/9/6Lg,HLUXXXg/NLH XX_ N XuXX6uNuOu66guR6i6 gggNg+vXgvvNvL_X_g_N_}HXHX6vHINXNguHN:bLbgN_H-RXbuRNN}1X1g1NbI5L7g1_{d,/}g0b}l}//u/N}bLXsvLNL!XX/gL/X#X} gXv iXHugXNu/6XuX6Nu1gXg}gNgOgTvggvv7_/_g___;_/HXHN_NNXvvNNNYbXHgb/bANARgbgRYbH1g1N169X1LnN) }X}g}N}h&_/g}g/!}1LgLNL,XXLvXNLR X g N RuXu/ Ou%u/6g}H6%gLgggNg=gl  vNvB_XX6_N_1HXvg_1H8H/NgHHN<HbbgbNN}RXbuRNRR1X161NRR1_pg1_&B1 }g}N}f.X}6/N}bLX/6LNLvXXLuX}X5L4 gL} CuXuguN L6Xu 6NubgX6XgNgc6Rvgg_vK_/_g_H_._RH}HNHLNX6HNNN1bXbubNbN_}RgRNRK_61g1H1T1/RgQNPL}XR6}N}B/X}u}R/q/uLg}LL*XXXg/NXv XX_ N /uX  uNXTub6guR6^6ugguHg9vXv/vNv/_Xvv_N_pHXHgHLH+H6NgNNN7N bgbgb RXRgRNuH1X161NRRRXJg1_0WR }g}N}WPX1v/N}RLX/uLN/6XX/gL}X{X} gXH A buguN v6Xuu6N6RgXgugNu_gNvgg_vY/u_g_H_Q6RHgHg6bNXNgNN /bXb6bNNRNXRgb_RON 1g1N1=RX_1yN1R}X&u}Ns6/XVg}g/m/}Lg/HL4LbXgXNLb XXu N RuXuuuNX_ ?6gu_6m?bgggHg=u1vgvg b_X_g_NLvHXH6HNHNg}NgNNNr ubgbHbEb/NgRNbR1XNv1N18pXRgbb7Mz/}go_}s(H/g;N/}LX/ LN/1XXX}XNX2XN gX_ Fu/ugu_u?XR 16NuRgX._gNg1vX6bvNvNu}_g_N_GLuHgHHHGHqg NNNYbX LbNb1RXNgb1R>R/1gRH1WRbwg<N1}}XGu}N}R/X/6/N}RL}Lg/_La/ XgXNX#LXX} NXbuX 6uNuv6Xuuu%6tu4ggu}gBvXvgvNgH_Xv _NvbHX_XHNHxHuNgH_N(b/bgbHb3bRR}RNRL1XgR1N11pXnuINaNb}}g}N}iH_/g/H/E//}gLNLLXX}6XNXr XXu/u k uugXLuj6X6g Nu gX6_gNg/vXu vN69gb_gvR_?_uHgv H=_XHuNNN/bXN_bNb/RXNgR/RrRu1gRR1tRLFg!N(/}XW_}N}}/X/g/N/G/XLg/1L>XXXgLbX&Xc}  N 3uXNLuNu16Xuu N6O6/gg bgYvXvg6N6}_Xvu_NvRHXv1HNv{HXNgHvNtNLbgb b<RXbuRNbR1X1u1N1RtXR/rHSQt/}g6v}:/L/g1u/x/f1 LNLnXX_ XNX1 XXuLN p /ugLbuc6X6g N/6gX6ugN6RvX61vN6Zvu_gvv_s_LHgH HZNXN/NNHRbXbubNbRRXN/R/RrR/1g 112iL!gR6tMtQb }N}o/XgH/N/1LXLX1vLlXXXg_vX+ L gX_L{uX uuNX}6X6g6N o/Hgg6_g=g/vggLvxgXvX_NvbHX_6HNHvNXNgH N;N/bgb_b-R/RgNub11XRu1N HfXh6pN1 }X}Xbv}7/X/gg6/9LLLg}NLLXXLuXNL1 XX} N ELHug _uj6/6g6H6C6Rg}gNgLvXtgvNv1_X_u_N_N6}HgHNH&LXNgNHNhN/HgbNbLRXH1RNRs1XbgNK1416.g11JeRu}go_06/X}v/N/LLXLgLNLs/bXgL1X!X  g _ BXX _uNuL6XuH6NuugX6u6LgWg vgu_v^_X_g_Nv_HX_gHNH!NXNgNNN<HNbgN1bxbXRgRHRZR/bg1N1LjXNR!NO<}Xmu11}x}u/g}7/aLXLgLNLuXXLHXNXR X 6 N N XuguNu8/K6g6H65gX66gNgPvXv6vNv>_X");local n=0;r.cCJASMpy(function()n=n+1 end)local function e(e,d)if d then return n end;n=e+n;end local d,n,u=g(0,g,e,a,r.KHKGclqo);local function f()local d,n=r.KHKGclqo(a,e(1,3),e(5,6)+2);e(2);return(n*256)+d;end;local c=true;local c=0 local function _()local l=n();local e=n();local t=1;local l=(d(e,1,20)*(2^32))+l;local n=d(e,21,31);local e=((-1)^d(e,32));if(n==0)then if(l==c)then return e*0;else n=1;t=0;end;elseif(n==2047)then return(l==0)and(e*(1/0))or(e*(0/0));end;return r.VxoQPLMW(e,n-1023)*(t+(l/(2^52)));end;local k=n;local function p(n)local d;if(not n)then n=k();if(n==0)then return'';end;end;d=r.PFHLgbIu(a,e(1,3),e(5,6)+n-1);e(n)local e=""for n=(1+c),#d do e=e..r.PFHLgbIu(d,n,n)end return e;end;local c=#r.U_OwdhcZ(b('\49.\48'))~=1 local e=n;local function de(...)return{...},r.R_BqpqzF('#',...)end local function le()local e={};local a={};local g={};local b={a,g,nil,e};local e=n()local h={}for l=1,e do local d=u();local e;if(d==1)then e=(u()~=#{});elseif(d==3)then local n=_();if c and r.EvDqTnBY(r.U_OwdhcZ(n),'.(\48+)$')then n=r.PGChSoAU(n);end e=n;elseif(d==2)then e=p();end;h[l]=e;end;for e=1,n()do g[e-(#{1})]=le();end;b[3]=u();for r=1,n()do local e=u();if(d(e,1,1)==0)then local g=d(e,2,3);local u=d(e,4,6);local e={f(),f(),nil,nil};if(g==0)then e[t]=f();e[o]=f();elseif(g==#{1})then e[t]=n();elseif(g==s[2])then e[t]=n()-(2^16)elseif(g==s[3])then e[t]=n()-(2^16)e[o]=f();end;if(d(u,1,1)==1)then e[l]=h[e[l]]end if(d(u,2,2)==1)then e[t]=h[e[t]]end if(d(u,3,3)==1)then e[o]=h[e[o]]end a[r]=e;end end;return b;end;local function te(d,n,e)local l=n;local l=e;return b(r.EvDqTnBY(r.EvDqTnBY(({r.cCJASMpy(d)})[2],n),e))end local function _(m,s,u)local function le(...)local f,k,p,ne,b,n,a,ee,z,j,c,d;local e=0;while-1<e do if e>2 then if 5<=e then if e==5 then d=g(7);else e=-2;end else if 0<=e then repeat if e~=4 then ee={};z={...};break;end;j=r.R_BqpqzF('#',...)-1;c={};until true;else j=r.R_BqpqzF('#',...)-1;c={};end end else if 0>=e then f=g(6,77,1,61,m);k=g(6,22,2,22,m);else if-1<=e then for d=22,77 do if e~=2 then p=g(6,13,3,54,m);b=de ne=0;break;end;n=-41;a=-1;break;end;else p=g(6,13,3,54,m);b=de ne=0;end end end e=e+1;end;for e=0,j do if(e>=p)then ee[e-p]=z[e+1];else d[e]=z[e+1];end;end;local e=j-p+1 local e;local g;local function p(...)while true do end end while true do if n<-40 then n=n+42 end e=f[n];g=e[y];if 47<=g then if 70>g then if 58<=g then if 64>g then if 61>g then if 59<=g then if 57<g then for n=36,61 do if g<60 then local n=e[l];local l=d[e[t]];d[n+1]=l;d[n]=l[e[o]];break;end;d[e[l]]={};break;end;else local l=e[l];local n=d[e[t]];d[l+1]=n;d[l]=n[e[o]];end else local g;for u=0,3 do if 1<u then if u>1 then for r=41,70 do if u~=3 then g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];break;end;if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;break;end;else g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];end else if 0<u then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end end end end else if g>61 then if 62==g then d[e[l]][e[t]]=e[o];else local n=e[l]d[n](h(d,n+1,e[t]))end else local f=e[l];local o=e[o];local l=f+2 local f={d[f](d[f+1],d[l])};for e=1,o do d[l+e]=f[e];end;local f=f[1]if f then d[l]=f n=e[t];else n=n+1;end;end end else if 67>g then if 64<g then if g>=62 then for u=11,92 do if g>65 then local e=e[l]d[e]=d[e](d[e+1])break;end;local u,a,r,s,k,_,c,b,g;for g=0,3 do if 1<g then if g~=3 then r=e[l];u=d[e[t]];d[r+1]=u;d[r]=u[e[o]];n=n+1;e=f[n];else g=0;while g>-1 do if g<3 then if g<=0 then s=e;else if 2==g then _=t;else k=l;end end else if 5<=g then if 1~=g then repeat if g>5 then g=-2;break;end;d(b,c);until true;else d(b,c);end else if 3<g then b=s[k];else c=s[_];end end end g=g+1 end end else if 1==g then r=e[l]d[r](h(d,r+1,e[t]))n=n+1;e=f[n];else u=e[t];a=d[u]for e=u+1,e[o]do a=a..d[e];end;d[e[l]]=a;n=n+1;e=f[n];end end end break;end;else local e=e[l]d[e]=d[e](d[e+1])end else local h,a,r;for g=0,6 do if 2<g then if g<5 then if 4~=g then h=e[l]a={d[h](d[h+1])};r=0;for e=h,e[o]do r=r+1;d[e]=a[r];end n=n+1;e=f[n];else d[e[l]]=u[e[t]];n=n+1;e=f[n];end else if 1<=g then repeat if 6~=g then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];until true;else d[e[l]]=d[e[t]][e[o]];end end else if 1<=g then if g>-3 then repeat if 1<g then d[e[l]]=d[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]];n=n+1;e=f[n];until true;else d[e[l]]=d[e[t]];n=n+1;e=f[n];end else d(e[l],e[t]);n=n+1;e=f[n];end end end end else if 68<=g then if 66<=g then for r=14,82 do if 69>g then local g,k,_,c,s;for r=0,6 do if r<3 then if 0<r then if-2<=r then repeat if 1~=r then d(e[l],e[t]);n=n+1;e=f[n];break;end;g=e[l];k=d[e[t]];d[g+1]=k;d[g]=k[e[o]];n=n+1;e=f[n];until true;else d(e[l],e[t]);n=n+1;e=f[n];end else d[e[l]]=u[e[t]];n=n+1;e=f[n];end else if r>4 then if 5<r then g=e[l]d[g]=d[g]()else g=e[l]d[g]=d[g](h(d,g+1,a))n=n+1;e=f[n];end else if r~=1 then for o=49,64 do if 4~=r then d[e[l]]=(e[t]~=0);n=n+1;e=f[n];break;end;g=e[l]_,c=b(d[g](h(d,g+1,e[t])))a=c+g-1 s=0;for e=g,a do s=s+1;d[e]=_[s];end;n=n+1;e=f[n];break;end;else g=e[l]_,c=b(d[g](h(d,g+1,e[t])))a=c+g-1 s=0;for e=g,a do s=s+1;d[e]=_[s];end;n=n+1;e=f[n];end end end end break;end;local g,r,o,f,u;local n=0;while n>-1 do if n>2 then if 4>=n then if 1<n then for e=45,93 do if 3~=n then u=g[r];break;end;f=g[o];break;end;else f=g[o];end else if 4<=n then repeat if 5<n then n=-2;break;end;d(u,f);until true;else d(u,f);end end else if 1>n then g=e;else if n~=-1 then for e=15,80 do if n~=2 then r=l;break;end;o=t;break;end;else o=t;end end end n=n+1 end break;end;else local f,r,o,g,u;local n=0;while n>-1 do if n>2 then if 4>=n then if 1<n then for e=45,93 do if 3~=n then u=f[r];break;end;g=f[o];break;end;else g=f[o];end else if 4<=n then repeat if 5<n then n=-2;break;end;d(u,g);until true;else d(u,g);end end else if 1>n then f=e;else if n~=-1 then for e=15,80 do if n~=2 then r=l;break;end;o=t;break;end;else o=t;end end end n=n+1 end end else n=e[t];end end end else if 52<=g then if 55>g then if 52<g then if g~=49 then repeat if g~=54 then local g;for u=0,3 do if 2>u then if u>-1 then for g=29,80 do if 1~=u then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if 3>u then g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end end end break;end;local g,_,s,k,r,c;for s=0,6 do if 2<s then if 4<s then if s<6 then g=e[l]c,k=b(d[g](d[g+1]))a=k+g-1 r=0;for e=g,a do r=r+1;d[e]=c[r];end;n=n+1;e=f[n];else g=e[l]c={d[g](h(d,g+1,a))};r=0;for e=g,e[o]do r=r+1;d[e]=c[r];end end else if s>3 then g=e[l];_=d[e[t]];d[g+1]=_;d[g]=_[e[o]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end end else if 1>s then d[e[l]]=u[e[t]];n=n+1;e=f[n];else if s~=2 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end end end end until true;else local u;for g=0,3 do if 2>g then if g>-1 then for u=29,80 do if 1~=g then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if 3>g then u=e[l]d[u]=d[u](d[u+1])n=n+1;e=f[n];else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end end end end else local e=e[l];do return d[e],d[e+1]end end else if 56<=g then if g~=56 then local e=e[l]d[e]=d[e](h(d,e+1,a))else d[e[l]]={};end else d[e[l]]=_(k[e[t]],nil,u);end end else if 49>g then if 44~=g then repeat if g<48 then local g;for u=0,3 do if u<=1 then if u==1 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if 1<u then repeat if 3>u then g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];break;end;if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;until true;else if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;end end end break;end;d[e[l]]=d[e[t]];until true;else local u;for g=0,3 do if g<=1 then if g==1 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if 1<g then repeat if 3>g then u=e[l]d[u]=d[u](d[u+1])n=n+1;e=f[n];break;end;if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;until true;else if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;end end end end else if 49<g then if g~=48 then for n=19,79 do if 50~=g then d[e[l]][e[t]]=e[o];break;end;d[e[l]]=u[e[t]];break;end;else d[e[l]][e[t]]=e[o];end else local e=e[l]d[e]=d[e](d[e+1])end end end end else if 82<=g then if 87>=g then if 84<g then if 86>g then local n=e[l]d[n]=d[n](h(d,n+1,e[t]))else if 82<=g then for n=19,80 do if 87>g then d[e[l]]=s[e[t]];break;end;do return end;break;end;else do return end;end end else if g>=83 then if 84>g then local g,r,a,b,c,s,_,u;g=e[l];r=d[e[t]];d[g+1]=r;d[g]=r[e[o]];n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];g=e[l]d[g]=d[g](h(d,g+1,e[t]))n=n+1;e=f[n];g=e[l];r=d[e[t]];d[g+1]=r;d[g]=r[e[o]];n=n+1;e=f[n];g=e[l]d[g](d[g+1])n=n+1;e=f[n];g=e[l];r=d[e[t]];d[g+1]=r;d[g]=r[e[o]];n=n+1;e=f[n];u=0;while u>-1 do if 3>u then if 1>u then a=e;else if 1~=u then c=t;else b=l;end end else if u>=5 then if 6==u then u=-2;else d(_,s);end else if 4>u then s=a[c];else _=a[b];end end end u=u+1 end else n=e[t];end else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end end else if g>90 then if g>91 then if g>90 then for u=33,71 do if 92~=g then local g,u;d[e[l]]=s[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];g=e[l];u=d[e[t]];d[g+1]=u;d[g]=u[e[o]];n=n+1;e=f[n];d[e[l]]=s[e[t]];n=n+1;e=f[n];g=e[l]d[g](h(d,g+1,e[t]))n=n+1;e=f[n];do return end;break;end;local l=e[l]local t={d[l](d[l+1])};local n=0;for e=l,e[o]do n=n+1;d[e]=t[n];end break;end;else local g,u;d[e[l]]=s[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];g=e[l];u=d[e[t]];d[g+1]=u;d[g]=u[e[o]];n=n+1;e=f[n];d[e[l]]=s[e[t]];n=n+1;e=f[n];g=e[l]d[g](h(d,g+1,e[t]))n=n+1;e=f[n];do return end;end else local g,r;d[e[l]]=u[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]];n=n+1;e=f[n];g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];g=e[l];r=d[e[t]];d[g+1]=r;d[g]=r[e[o]];n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];g=e[l]d[g]=d[g](h(d,g+1,e[t]))end else if 89>g then d[e[l]]=s[e[t]];else if g>89 then d[e[l]]=(e[t]~=0);else local u;for g=0,3 do if g<=1 then if g>-4 then for u=16,95 do if g~=0 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if g>=1 then repeat if g~=2 then if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;break;end;u=e[l]d[u]=d[u](d[u+1])n=n+1;e=f[n];until true;else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end end end end end end end else if 75>=g then if g>=73 then if 74>g then do return d[e[l]]end else if 73<=g then for f=40,77 do if g<75 then if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;break;end;s[e[t]]=d[e[l]];break;end;else s[e[t]]=d[e[l]];end end else if g<71 then local n=e[l]d[n](h(d,n+1,e[t]))else if g<72 then local n=e[l]local l,e=b(d[n](h(d,n+1,e[t])))a=e+n-1 local e=0;for n=n,a do e=e+1;d[n]=l[e];end;else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end end end else if g>78 then if 80>g then local g,h;for r=0,6 do if 3<=r then if 4>=r then if-1~=r then repeat if 4>r then g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];until true;else g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];end else if 1~=r then repeat if 6>r then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;g=e[l];h=d[e[t]];d[g+1]=h;d[g]=h[e[o]];until true;else g=e[l];h=d[e[t]];d[g+1]=h;d[g]=h[e[o]];end end else if r>0 then if r>-1 then for g=30,82 do if r<2 then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=u[e[t]];n=n+1;e=f[n];end else d[e[l]]=u[e[t]];n=n+1;e=f[n];end end end else if g~=76 then repeat if 81>g then for g=0,3 do if g<=1 then if-1~=g then repeat if g~=0 then u[e[t]]=d[e[l]];n=n+1;e=f[n];break;end;d[e[l]]=(e[t]~=0);n=n+1;e=f[n];until true;else u[e[t]]=d[e[l]];n=n+1;e=f[n];end else if 2~=g then if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;else d[e[l]]=u[e[t]];n=n+1;e=f[n];end end end break;end;local g,h,r;g=e[l]d[g](d[g+1])n=n+1;e=f[n];d[e[l]]=u[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];h=e[t];r=d[h]for e=h+1,e[o]do r=r..d[e];end;d[e[l]]=r;n=n+1;e=f[n];g=e[l]d[g](d[g+1])until true;else local g,h,r;g=e[l]d[g](d[g+1])n=n+1;e=f[n];d[e[l]]=u[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];h=e[t];r=d[h]for e=h+1,e[o]do r=r..d[e];end;d[e[l]]=r;n=n+1;e=f[n];g=e[l]d[g](d[g+1])end end else if g>76 then if g>=74 then for n=35,62 do if 77<g then local b,a,h,u,g,r,f;local n=0;while n>-1 do if n>2 then if 5<=n then if 4<n then for e=26,53 do if 6>n then d[r]=f;break;end;n=-2;break;end;else d[r]=f;end else if 1~=n then repeat if 3<n then f=d[g];for e=1+g,u[h]do f=f..d[e];end;break;end;r=u[b];until true;else f=d[g];for e=1+g,u[h]do f=f..d[e];end;end end else if n<1 then b=l;a=t;h=o;else if-1~=n then for d=47,57 do if n<2 then u=e;break;end;g=u[a];break;end;else g=u[a];end end end n=n+1 end break;end;local r,h,a,f,u,b,g;local n=0;while n>-1 do if n<3 then if 1>n then r=l;h=t;a=o;else if-2<=n then for d=16,82 do if 1~=n then u=f[h];break;end;f=e;break;end;else f=e;end end else if n<=4 then if 3~=n then g=d[u];for e=1+u,f[a]do g=g..d[e];end;else b=f[r];end else if n~=5 then n=-2;else d[b]=g;end end end n=n+1 end break;end;else local b,h,a,g,u,r,f;local n=0;while n>-1 do if n>2 then if 5<=n then if 4<n then for e=26,53 do if 6>n then d[r]=f;break;end;n=-2;break;end;else d[r]=f;end else if 1~=n then repeat if 3<n then f=d[u];for e=1+u,g[a]do f=f..d[e];end;break;end;r=g[b];until true;else f=d[u];for e=1+u,g[a]do f=f..d[e];end;end end else if n<1 then b=l;h=t;a=o;else if-1~=n then for d=47,57 do if n<2 then g=e;break;end;u=g[h];break;end;else u=g[h];end end end n=n+1 end end else local l=e[l]local t={d[l](h(d,l+1,a))};local n=0;for e=l,e[o]do n=n+1;d[e]=t[n];end end end end end end else if 23<=g then if 34>=g then if 29<=g then if 31>=g then if g<30 then local o;for g=0,2 do if g>=1 then if g>=-1 then for u=16,67 do if g<2 then o=e[l]d[o](d[o+1])n=n+1;e=f[n];break;end;n=e[t];break;end;else o=e[l]d[o](d[o+1])n=n+1;e=f[n];end else d(e[l],e[t]);n=n+1;e=f[n];end end else if g>27 then repeat if g~=30 then local g,a,h;for r=0,5 do if r>=3 then if r<=3 then d(e[l],e[t]);n=n+1;e=f[n];else if 3~=r then for u=49,54 do if r<5 then a=e[t];h=d[a]for e=a+1,e[o]do h=h..d[e];end;d[e[l]]=h;n=n+1;e=f[n];break;end;g=e[l]d[g](d[g+1])break;end;else g=e[l]d[g](d[g+1])end end else if 0<r then if r~=2 then d[e[l]]=u[e[t]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else g=e[l]d[g](d[g+1])n=n+1;e=f[n];end end end break;end;d(e[l],e[t]);until true;else local g,a,h;for r=0,5 do if r>=3 then if r<=3 then d(e[l],e[t]);n=n+1;e=f[n];else if 3~=r then for u=49,54 do if r<5 then a=e[t];h=d[a]for e=a+1,e[o]do h=h..d[e];end;d[e[l]]=h;n=n+1;e=f[n];break;end;g=e[l]d[g](d[g+1])break;end;else g=e[l]d[g](d[g+1])end end else if 0<r then if r~=2 then d[e[l]]=u[e[t]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else g=e[l]d[g](d[g+1])n=n+1;e=f[n];end end end end end else if g>=33 then if g>31 then repeat if g~=33 then local r;for g=0,6 do if g<=2 then if g<=0 then d[e[l]]={};n=n+1;e=f[n];else if g<2 then d[e[l]]=u[e[t]];n=n+1;e=f[n];else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end end else if g<=4 then if 0<g then for o=40,89 do if g<4 then d(e[l],e[t]);n=n+1;e=f[n];break;end;d(e[l],e[t]);n=n+1;e=f[n];break;end;else d(e[l],e[t]);n=n+1;e=f[n];end else if 4~=g then for o=24,63 do if g~=6 then d(e[l],e[t]);n=n+1;e=f[n];break;end;r=e[l]d[r]=d[r](h(d,r+1,e[t]))break;end;else r=e[l]d[r]=d[r](h(d,r+1,e[t]))end end end end break;end;local b,a,s,_,c,g,r;d[e[l]]=u[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];g=0;while g>-1 do if g>2 then if g>=5 then if g>=2 then for e=32,87 do if g>5 then g=-2;break;end;d(c,_);break;end;else g=-2;end else if g==4 then c=b[a];else _=b[s];end end else if 1>g then b=e;else if-2<g then for e=15,95 do if g>1 then s=t;break;end;a=l;break;end;else a=l;end end end g=g+1 end n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];r=e[l]d[r]=d[r](h(d,r+1,e[t]))n=n+1;e=f[n];d[e[l]][e[t]]=d[e[o]];n=n+1;e=f[n];d[e[l]][e[t]]=e[o];until true;else local b,a,s,c,_,g,r;d[e[l]]=u[e[t]];n=n+1;e=f[n];d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];g=0;while g>-1 do if g>2 then if g>=5 then if g>=2 then for e=32,87 do if g>5 then g=-2;break;end;d(_,c);break;end;else g=-2;end else if g==4 then _=b[a];else c=b[s];end end else if 1>g then b=e;else if-2<g then for e=15,95 do if g>1 then s=t;break;end;a=l;break;end;else a=l;end end end g=g+1 end n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];r=e[l]d[r]=d[r](h(d,r+1,e[t]))n=n+1;e=f[n];d[e[l]][e[t]]=d[e[o]];n=n+1;e=f[n];d[e[l]][e[t]]=e[o];end else d[e[l]]=u[e[t]];end end else if g<26 then if g<=23 then for e=e[l],e[t]do d[e]=nil;end;else if 25>g then local a=k[e[t]];local h;local g={};h=r.pvnBhPCy({},{__index=function(n,e)local e=g[e];return e[1][e[2]];end,__newindex=function(d,e,n)local e=g[e]e[1][e[2]]=n;end;});for l=1,e[o]do n=n+1;local e=f[n];if e[y]==48 then g[l-1]={d,e[t]};else g[l-1]={s,e[t]};end;c[#c+1]=g;end;d[e[l]]=_(a,h,u);else if d[e[l]]then n=n+1;else n=e[t];end;end end else if g<=26 then local o,s,r,g;for u=0,2 do if u<=0 then o=e[l]s,r=b(d[o](d[o+1]))a=r+o-1 g=0;for e=o,a do g=g+1;d[e]=s[g];end;n=n+1;e=f[n];else if-3<=u then repeat if u~=1 then if d[e[l]]then n=n+1;else n=e[t];end;break;end;o=e[l]d[o]=d[o](h(d,o+1,a))n=n+1;e=f[n];until true;else if d[e[l]]then n=n+1;else n=e[t];end;end end end else if 24~=g then for n=26,57 do if 27<g then local e=e[l]d[e]=d[e]()break;end;local e=e[l]local l,n=b(d[e](d[e+1]))a=n+e-1 local n=0;for e=e,a do n=n+1;d[e]=l[n];end;break;end;else local e=e[l]d[e]=d[e]()end end end end else if g>40 then if 43<g then if g<=44 then local u,r,b,a,s,c,_,g;u=e[l];r=d[e[t]];d[u+1]=r;d[u]=r[e[o]];n=n+1;e=f[n];d(e[l],e[t]);n=n+1;e=f[n];u=e[l]d[u]=d[u](h(d,u+1,e[t]))n=n+1;e=f[n];u=e[l];r=d[e[t]];d[u+1]=r;d[u]=r[e[o]];n=n+1;e=f[n];g=0;while g>-1 do if g<3 then if 0<g then if g~=-2 then for e=28,80 do if 1<g then s=t;break;end;a=l;break;end;else a=l;end else b=e;end else if g<=4 then if 4==g then _=b[a];else c=b[s];end else if 1~=g then for e=13,79 do if g<6 then d(_,c);break;end;g=-2;break;end;else g=-2;end end end g=g+1 end n=n+1;e=f[n];d[e[l]]=(e[t]~=0);n=n+1;e=f[n];u=e[l]d[u](h(d,u+1,e[t]))else if 43<g then repeat if 46~=g then do return d[e[l]]end break;end;d[e[l]]=d[e[t]][e[o]];until true;else d[e[l]]=d[e[t]][e[o]];end end else if g<42 then local e=e[l]d[e](d[e+1])else if g<43 then local n=e[l]d[n]=d[n](h(d,n+1,e[t]))else local n=e[l]local l,e=b(d[n](h(d,n+1,e[t])))a=e+n-1 local e=0;for n=n,a do e=e+1;d[n]=l[e];end;end end end else if 37>=g then if g>=36 then if g>=33 then repeat if g<37 then u[e[t]]=d[e[l]];break;end;local u;for g=0,3 do if 2<=g then if g>=0 then repeat if g~=2 then if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;break;end;u=e[l]d[u]=d[u](d[u+1])n=n+1;e=f[n];until true;else if(d[e[l]]==e[o])then n=n+1;else n=e[t];end;end else if-3~=g then for u=41,53 do if 0<g then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end end end until true;else u[e[t]]=d[e[l]];end else local e=e[l];do return d[e],d[e+1]end end else if g>=39 then if 35~=g then for h=23,55 do if 40~=g then local e=e[l]d[e]=d[e]()break;end;local a=k[e[t]];local h;local g={};h=r.pvnBhPCy({},{__index=function(n,e)local e=g[e];return e[1][e[2]];end,__newindex=function(d,e,n)local e=g[e]e[1][e[2]]=n;end;});for l=1,e[o]do n=n+1;local e=f[n];if e[y]==48 then g[l-1]={d,e[t]};else g[l-1]={s,e[t]};end;c[#c+1]=g;end;d[e[l]]=_(a,h,u);break;end;else local a=k[e[t]];local h;local g={};h=r.pvnBhPCy({},{__index=function(n,e)local e=g[e];return e[1][e[2]];end,__newindex=function(d,e,n)local e=g[e]e[1][e[2]]=n;end;});for l=1,e[o]do n=n+1;local e=f[n];if e[y]==48 then g[l-1]={d,e[t]};else g[l-1]={s,e[t]};end;c[#c+1]=g;end;d[e[l]]=_(a,h,u);end else local n=e[l]local t={d[n](h(d,n+1,a))};local l=0;for e=n,e[o]do l=l+1;d[e]=t[l];end end end end end else if 11<=g then if g<17 then if 13>=g then if g<12 then d[e[l]]=_(k[e[t]],nil,u);else if 9~=g then for r=16,95 do if 13~=g then local g,_,s,k,r,c;for s=0,6 do if s>2 then if s>=5 then if s~=5 then g=e[l]c={d[g](h(d,g+1,a))};r=0;for e=g,e[o]do r=r+1;d[e]=c[r];end else g=e[l]c,k=b(d[g](d[g+1]))a=k+g-1 r=0;for e=g,a do r=r+1;d[e]=c[r];end;n=n+1;e=f[n];end else if s>=2 then for r=13,87 do if 4>s then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;g=e[l];_=d[e[t]];d[g+1]=_;d[g]=_[e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=u[e[t]];n=n+1;e=f[n];end end else if s>=1 then if-2~=s then repeat if s~=1 then g=e[l]d[g]=d[g]()n=n+1;e=f[n];break;end;d[e[l]]=u[e[t]];n=n+1;e=f[n];until true;else g=e[l]d[g]=d[g]()n=n+1;e=f[n];end else g=e[l]d[g]=d[g]()n=n+1;e=f[n];end end end break;end;local l=e[l];local n=d[e[t]];d[l+1]=n;d[l]=n[e[o]];break;end;else local l=e[l];local n=d[e[t]];d[l+1]=n;d[l]=n[e[o]];end end else if 15>g then local g,_,s,k,r,c;for s=0,5 do if s<3 then if 0<s then if-2<s then for u=27,54 do if 2>s then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;g=e[l];_=d[e[t]];d[g+1]=_;d[g]=_[e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else d[e[l]]=u[e[t]];n=n+1;e=f[n];end else if 4>s then g=e[l]c,k=b(d[g](d[g+1]))a=k+g-1 r=0;for e=g,a do r=r+1;d[e]=c[r];end;n=n+1;e=f[n];else if 4==s then g=e[l]c={d[g](h(d,g+1,a))};r=0;for e=g,e[o]do r=r+1;d[e]=c[r];end n=n+1;e=f[n];else n=e[t];end end end end else if g>11 then repeat if 16>g then d[e[l]]=d[e[t]][e[o]];break;end;local l=e[l]local t={d[l](d[l+1])};local n=0;for e=l,e[o]do n=n+1;d[e]=t[n];end until true;else d[e[l]]=d[e[t]][e[o]];end end end else if g>19 then if 20<g then if g~=17 then for u=41,65 do if g~=22 then local e=e[l]local l,n=b(d[e](d[e+1]))a=n+e-1 local n=0;for e=e,a do n=n+1;d[e]=l[n];end;break;end;local g,u;for r=0,2 do if 1<=r then if 1==r then g=e[l];u=d[e[t]];d[g+1]=u;d[g]=u[e[o]];n=n+1;e=f[n];else d(e[l],e[t]);end else g=e[l]d[g](h(d,g+1,e[t]))n=n+1;e=f[n];end end break;end;else local g,u;for r=0,2 do if 1<=r then if 1==r then g=e[l];u=d[e[t]];d[g+1]=u;d[g]=u[e[o]];n=n+1;e=f[n];else d(e[l],e[t]);end else g=e[l]d[g](h(d,g+1,e[t]))n=n+1;e=f[n];end end end else if d[e[l]]then n=n+1;else n=e[t];end;end else if 17<g then if g>17 then for n=19,71 do if g~=18 then d[e[l]][e[t]]=d[e[o]];break;end;d[e[l]][e[t]]=d[e[o]];break;end;else d[e[l]][e[t]]=d[e[o]];end else do return end;end end end else if g>=5 then if g>7 then if g>8 then if g>=5 then for n=32,83 do if 10>g then d[e[l]]=d[e[t]];break;end;local e=e[l]d[e](d[e+1])break;end;else d[e[l]]=d[e[t]];end else for e=e[l],e[t]do d[e]=nil;end;end else if g>5 then if g>6 then local f=e[l];local o=e[o];local l=f+2 local f={d[f](d[f+1],d[l])};for e=1,o do d[l+e]=f[e];end;local f=f[1]if f then d[l]=f n=e[t];else n=n+1;end;else local e=e[l]d[e]=d[e](h(d,e+1,a))end else d[e[l]]=(e[t]~=0);end end else if g>=2 then if g<3 then s[e[t]]=d[e[l]];else if 1<g then repeat if g~=3 then if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;break;end;local g;for u=0,3 do if u<2 then if-2<u then repeat if u~=1 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];until true;else d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];end else if u>=-2 then for r=46,56 do if u>2 then if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;break;end;g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];break;end;else g=e[l]d[g]=d[g](d[g+1])n=n+1;e=f[n];end end end until true;else if(d[e[l]]~=e[o])then n=n+1;else n=e[t];end;end end else if g>=-3 then for r=13,56 do if 0<g then local r;for g=0,6 do if g>=3 then if 4<g then if g~=2 then for r=16,80 do if g<6 then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];break;end;else d[e[l]]=d[e[t]][e[o]];end else if g==3 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else r=e[l]d[r]=d[r](d[r+1])n=n+1;e=f[n];end end else if g<1 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else if g~=0 then for r=22,52 do if 2>g then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=u[e[t]];n=n+1;e=f[n];end end end end break;end;u[e[t]]=d[e[l]];break;end;else local r;for g=0,6 do if g>=3 then if 4<g then if g~=2 then for r=16,80 do if g<6 then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];break;end;else d[e[l]]=d[e[t]][e[o]];end else if g==3 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else r=e[l]d[r]=d[r](d[r+1])n=n+1;e=f[n];end end else if g<1 then d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];else if g~=0 then for r=22,52 do if 2>g then d[e[l]]=u[e[t]];n=n+1;e=f[n];break;end;d[e[l]]=d[e[t]][e[o]];n=n+1;e=f[n];break;end;else d[e[l]]=u[e[t]];n=n+1;e=f[n];end end end end end end end end end end n=1+n;end;end;return le end;local l=0xff;local u={};local o=(1);local t='';(function(n)local d=n local f=0x00 local e=0x00 d={(function(g)if f>0x21 then return g end f=f+1 e=(e+0xbff-g)%0x2b return(e%0x03==0x0 and(function(d)if not n[d]then e=e+0x01 n[d]=(0xc);t='\37';l={function()l()end};t=t..'\100\43';end return true end)'yBfme'and d[0x1](0x208+g))or(e%0x03==0x1 and(function(d)if not n[d]then e=e+0x01 n[d]=(0x43);end return true end)'FvafJ'and d[0x2](g+0x186))or(e%0x03==0x2 and(function(d)if not n[d]then e=e+0x01 n[d]=(0x29);t={t..'\58 a',t};u[o]=le();o=o+(1);t[1]='\58'..t[1];l[2]=0xff;end return true end)'kMzDK'and d[0x3](g+0x15d))or g end),(function(t)if f>0x28 then return t end f=f+1 e=(e+0xa95-t)%0x1f return(e%0x03==0x0 and(function(d)if not n[d]then e=e+0x01 n[d]=(0xc);end return true end)'iCtpv'and d[0x3](0x2b7+t))or(e%0x03==0x2 and(function(d)if not n[d]then e=e+0x01 n[d]=(0x8e);end return true end)'hEtCu'and d[0x1](t+0x27e))or(e%0x03==0x1 and(function(d)if not n[d]then e=e+0x01 n[d]=(0x89);u[o]=fe();o=o+l;end return true end)'HHvCA'and d[0x2](t+0x343))or t end),(function(g)if f>0x25 then return g end f=f+1 e=(e+0xe6a-g)%0x24 return(e%0x03==0x0 and(function(d)if not n[d]then e=e+0x01 n[d]=(0xa);end return true end)'tqQLG'and d[0x1](0x39e+g))or(e%0x03==0x1 and(function(d)if not n[d]then e=e+0x01 n[d]=(0xbe);end return true end)'FYSwJ'and d[0x3](g+0xad))or(e%0x03==0x2 and(function(d)if not n[d]then e=e+0x01 n[d]=(0xd8);l[2]=(l[2]*(te(function()u()end,h(t))-te(l[1],h(t))))+1;u[o]={};l=l[2];o=o+l;end return true end)'Ujcif'and d[0x2](g+0x3dd))or g end)}d[0x1](0x260c)end){};local e=_(h(u));return e(...);end return te((function()local n={}local e=0x01;local d;if r.gxHafamD then d=r.gxHafamD(te)else d=''end if r.EvDqTnBY(d,r.oTFmWioj)then e=e+0;else e=e+1;end n[e]=0x02;n[n[e]+0x01]=0x03;return n;end)(),...)end)((function(d,e,n,l,t,f)local f;if 4<=d then if 5<d then if d<7 then do return t[n]end;else if 8==d then do return n(d,nil,n);end else do return setmetatable({},{['__\99\97\108\108']=function(e,d,l,t,n)if n then return e[n]elseif t then return e else e[d]=l end end})end end end else if d~=3 then repeat if 5>d then local d=l;local g,l,t=t(2);do return function()local o,f,n,e=e(n,d(d,d),d(d,d)+3);d(4);return(e*g)+(n*l)+(f*t)+o;end;end;break;end;local d=l;do return function()local e=e(n,d(d,d),d(d,d));d(1);return e;end;end;until true;else local d=l;local t,f,l=t(2);do return function()local e,o,n,g=e(n,d(d,d),d(d,d)+3);d(4);return(g*t)+(n*f)+(o*l)+e;end;end;end end else if d<=1 then if d>-2 then repeat if d>0 then do return function(n,e,d)if d then local e=(n/2^(e-1))%2^((d-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(n%(e+e)>=e)and 1 or 0;end;end;end;break;end;do return e(1),e(4,t,l,n,e),e(5,t,l,n)end;until true;else do return function(n,e,d)if d then local e=(n/2^(e-1))%2^((d-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(n%(e+e)>=e)and 1 or 0;end;end;end;end else if d~=0 then repeat if d~=2 then do return e(1),e(4,t,l,n,e),e(5,t,l,n)end;break;end;do return 16777216,65536,256 end;until true;else do return e(1),e(4,t,l,n,e),e(5,t,l,n)end;end end end end),...)
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 

‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
      ‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
‎ 
